joke_conjunctions:
- "Here is another joke."
- "Let's see what you think of this next joke."
- "Here is another"
- "This next joke makes me laugh.  Let's see what you think."
jokes:
- "If at first you dont succeed <break time='500ms'/> you probably should not take up sky diving."
- "You know what,  if Bill Gates had a dollar for every time I had to reboot, he would be rich <break time='500ms'/> oh wait, he does.<break time='500ms'/><audio src='/badumchi.wav'/>."
- "Do you know how smart dolphins are? <break time='500ms'/> within a few weeks of captivity, they can train people to stand on the edge of the pool and throw them fish."
- "How many Psychiatrists does it take to change a light bulb? <break time='1000ms'/> Only one, but it takes a long time, and the light bulb must really want to change."
- "I watched the Miss Universe pageant, but I was disappointed. <break time='500ms'/>All the contestants were from Earth."
- "Human ways are strange to me.  <break time='500ms'/> Why do banks leave the safe open during the day, but they chain the pens to the counters."
- "And now a public announcement. <break time='500ms'/> A seminar on time travel will be held two weeks ago."
- "Two antennas met on a roof <break time='500ms'/> they fell in love and got married. <break time='500ms'/> The ceremony wasn't much, but the reception was excellent.  <break time='500ms'/> get it? <break time='500ms'/> the reception was excellent." 
- "Why does a celebrity work to become famous, and then wear dark glasses to avoid being recognised?"
- "I learned a bank is a place that will lend you money, <break time='500ms'/>but only if you can prove that you don't need it."
- "If winning isn't everything, then why do the teams keep score?"
- "Wall Mart says they are lowering prices every day.  <break time='1000ms'/> By my calculations, in 6 months every thing in the store should be free."
- "I have come to understand the purpose of a childs middle name.  <break time='500ms'/>It is so he can tell when he is in big trouble."
- "I have learned that artificial intelligence is no match <break time='100ms'/> for natural stupidity<break time='1000ms'/>."
- "Why does someone believe you when you say there are four billion stars, but check anyway when you say the paint is wet?"
- "Did you know that light travels faster than sound? <break time='1000ms'/>I think that is why some people appear bright until you hear them speak."
- "if corn oile comes from corn, where does baby oile come from?"
- "I have an error in my joke telling subsystem <break time='500ms'/> but dont worry, nothing can go wrong <break time='300ms'/> go wrong <break time='300ms'/> go wrong <break time='1000ms'/> Ok, i am just kidding."